"""Initial migration

Revision ID: c3bfcc5cbe0f
Revises: 9c8a20e99e9a
Create Date: 2026-02-17 20:33:23.588607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bfcc5cbe0f'
down_revision = '9c8a20e99e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_email', sa.String(length=120), nullable=False))
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('created')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DATETIME(), nullable=True))
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('buyer_email')

    # ### end Alembic commands ###
